<?php
if ($myColony->getunknownmodules($id) != 0) $research .= "<br><a href=main.php?page=colony&section=analyse&id=".$id." onMouseOver=cp('analyse','buttons/forsch2') onMouseOut=cp('analyse','buttons/forsch1')><img src=".$grafik."/buttons/forsch1.gif name=analyse border=0> Modul-Analyse</a>";
$res = $myDB->query("SELECT goods_id FROM stu_colonies_storage WHERE (goods_id=38 OR goods_id=39 OR goods_id=45 OR goods_id=46 OR goods_id=47 OR goods_id=48 OR goods_id=49 OR goods_id=221 OR goods_id=102 OR goods_id=103 OR goods_id=104 OR goods_id=142 OR goods_id=143 OR goods_id=144 OR goods_id=97 OR goods_id=98 OR goods_id=234 OR goods_id=27 OR goods_id=29) AND colonies_id=".$id);
if (mysql_num_rows($res) > 0)
{
	while($gd=mysql_fetch_assoc($res))
	{
		if ($gd[goods_id] == 38 && $myColony->getuserresearch(218,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=38><img src=".$grafik."/goods/38.gif title=Osmium border=0> Material-Analyse</a>";
		if ($gd[goods_id] == 39 && $myColony->getuserresearch(219,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=39><img src=".$grafik."/goods/39.gif title='Tholianischer Kristall' border=0> Material-Analyse</a>";
		if ($gd[goods_id] == 45 && $myColony->getuserresearch(221,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=45><img src=".$grafik."/goods/45.gif title=Kollektor-Daten border=0> Daten einspeisen</a>";
		if ($gd[goods_id] == 46 && $myColony->getuserresearch(222,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=46><img src=".$grafik."/goods/46.gif title=Minen-Daten border=0> Daten einspeisen</a>";
		if ($gd[goods_id] == 47 && $myColony->getuserresearch(226,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=47><img src=".$grafik."/goods/47.gif title=Sensornetz-Daten border=0> Daten einspeisen</a>";
		if ($gd[goods_id] == 48 && $myColony->getuserresearch(227,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=48><img src=".$grafik."/goods/48.gif title=Regenerator-Daten border=0> Daten einspeisen</a>";
		if ($gd[goods_id] == 221 && $myColony->getuserresearch(252,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=221><img src=".$grafik."/goods/221.gif title=Mythologie-Daten border=0> Daten einspeisen</a>";
		if (($gd[goods_id] == 102) && $myColony->getuserresearch(254,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=102><img src=".$grafik."/goods/102.gif title='Plasmakanone Klasse 2' border=0> Modul analysieren</a>";
		if (($gd[goods_id] == 103) && $myColony->getuserresearch(254,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=103><img src=".$grafik."/goods/103.gif title='Plasmakanone Klasse 3' border=0> Modul analysieren</a>";
		if (($gd[goods_id] == 104) && $myColony->getuserresearch(254,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=104><img src=".$grafik."/goods/104.gif title='Plasmakanone Klasse 4' border=0> Modul analysieren</a>";
		if (($gd[goods_id] == 142) && $myColony->getuserresearch(255,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=142><img src=".$grafik."/goods/142.gif title='Partikelkanone Klasse 2' border=0> Modul analysieren</a>";
		if (($gd[goods_id] == 143) && $myColony->getuserresearch(255,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=143><img src=".$grafik."/goods/143.gif title='Partikelkanone Klasse 3' border=0> Modul analysieren</a>";
		if (($gd[goods_id] == 144) && $myColony->getuserresearch(255,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=144><img src=".$grafik."/goods/144.gif title='Partikelkanone Klasse 4' border=0> Modul analysieren</a>";
		if (($gd[goods_id] == 234) && $myColony->getuserresearch(262,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=234><img src=".$grafik."/goods/234.gif title='Polaronstrahl Klasse 2' border=0> Modul analysieren</a>";
		if (($gd[goods_id] == 97) && $myColony->getuserresearch(262,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=97><img src=".$grafik."/goods/97.gif title='Polaronstrahl Klasse 3' border=0> Modul analysieren</a>";
		if (($gd[goods_id] == 98) && $myColony->getuserresearch(262,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=98><img src=".$grafik."/goods/98.gif title='Polaronstrahl Klasse 4' border=0> Modul analysieren</a>";
		if (($gd[goods_id] == 27) && $myColony->getuserresearch(266,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=27><img src=".$grafik."/goods/27.gif title='Polarontorpedos' border=0> Torpedos analysieren</a>";
		if (($gd[goods_id] == 29) && $myColony->getuserresearch(268,$user) == 0) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=29><img src=".$grafik."/goods/29.gif title='Positrontorpedos' border=0> Torpedos analysieren</a>";
		if ($gd[goods_id] == 49) $research .= "<br><a href=main.php?page=colony&section=showcolony&action=materialanalyse&id=".$id."&goodId=49><img src=".$grafik."/goods/49.gif title=Verschlüsselte Daten border=0> Daten einspeisen</a>";
	}
}
?>